[package]
name = "accounter"
version = "0.1.0"
edition = "2021"
authors = ["Tibor Prokai"]

[dependencies]
rust_decimal = "1.23"
pest = "2.1"
pest_derive = "2.1"

[features]
default = ["error-print"] 
error-print = []